<?php

$a_products=
[

    1=>[
        'id_product'=> 1,
        'index' => 1,
        'name'=>'Remera jaspeada',
        'price'=>'$600',
        'description'=>'Talles del S al XXL.'."<br>".'Material: algodon peinado.'."<br>".'Colores:negro, blanco, azul.'."<br>".'Marca: Puma',
        'id_category'=>1,
    ],
    2=>[
        'id_product'=> 2,
        'index' => 2,
        'name'=>'Remera deportiva fluor',
        'price'=>'$800',
        'description'=>'Talles del S al XL.'."<br>".'Material:Jersey dep.'."<br>".'Colores:negro, verde y naranja.'."<br>".'Marca:Puma',
        'id_category'=>1,
    ],
    3=>[
        'id_product'=> 3,
        'index' => 3,
        'name'=>'Remera playera',
        'price'=>'$700',
        'description'=>'Talles del S al XXL.'."<br>".'Material: algodon .'."<br>".'Colores:negro y gris oscuro.'."<br>".'Marca:Puma',
        'id_category'=>1,
    ],
    4=>[
        'id_product'=> 4,
        'index' => 4,
        'name'=>'Camiseta futbolera',
        'price'=>'$900',
        'description'=>'Talles del S al XXXL.'."<br>".'Material: Winfresh  .'."<br>".'Colores:negro y blanco.'."<br>".'Marca: Puma',
        'id_category'=>1,
    ],
    5=>[
        'id_product'=> 5,
        'index' => 5,
        'name'=>'Remera estampa grande',
        'price'=>'$800',
        'description'=>'Talles del M al XL.'."<br>".'Material: algodon peinado .'."<br>".'Colores:rosa, verde y rojo.'."<br>".'Marca: Puma',
        'id_category'=>1,
    ],
    6=>[
        'id_product'=> 1,
        'index' => 6,
        'name'=>'Jogging simple',
        'price'=>'$900',
        'description'=>'Talles del M al XXL.'."<br>".'Material: algodon rustico .'."<br>".'Colores:negro, melange y gris.'."<br>".'Marca: Puma',
        'id_category'=>2,
    ],
    7=>[
        'id_product'=> 2,
        'index' => 7,
        'name'=>'Jogging franja entera',
        'price'=>'$950',
        'description'=>'Talles del S al XXL.'."<br>".'Material: algodon rustico .'."<br>".'Colores:negro y melange .'."<br>".'Marca: Puma',
        'id_category'=>2,
    ],
    8=>[
        'id_product'=> 3,
        'index' => 8,
        'name'=>'Jogging media franja',
        'price'=>'$1000',
        'description'=>'Talles del S al XXL.'."<br>".'Material: algodon rustico .'."<br>".'Colores:negro, azul francia y gris.'."<br>".'Marca: Puma',
        'id_category'=>2,
    ],
    9=>[
        'id_product'=> 4,
        'index' => 9,
        'name'=>'Pantalon parches',
        'price'=>'$1200',
        'description'=>'Talle unico.'."<br>".'Material:Rompeviento .'."<br>".'Colores:negro y blanco.'."<br>".'Marca: Puma',
        'id_category'=>2,
    ],
    10=>[
        'id_product'=> 5,
        'index' => 10,
        'name'=>'Jogging puma grande',
        'price'=>'$1100',
        'description'=>'Talles del M al XXL.'."<br>".'Material: algodon rustico .'."<br>".'Colores:negro, blanco y gris.'."<br>".'Marca: Puma',
        'id_category'=>2,
    ],
    11=>[
        'id_product'=> 1,
        'index' => 11,
        'name'=>'Zapatillas tricolor',
        'price'=>'$2200',
        'description'=>"<br>".'Talles del 36 al 46.'."<br>".'Colores:negro, blanco y rojo.'."<br>".'Marca: Puma',
        'id_category'=>3,
    ],
    12=>[
        'id_product'=> 2,
        'index' => 12,
        'name'=>'Ojotas puma',
        'price'=>'$1400',
        'description'=>"<br>".'Talles del 36 al 45.'."<br>".'Colores:negro y blanco'."<br>".'Marca: Puma',
        'id_category'=>3,
    ],
    13=>[
        'id_product'=> 3,
        'index' => 13,
        'name'=>'Zapatillas deportiva',
        'price'=>'$2900',
        'description'=>"<br>".'Talles del 37 al 44.'."<br>".'Colores:negro y rojo.'."<br>".'Marca: Puma',
        'id_category'=>3,
    ],
    14=>[
        'id_product'=> 4,
        'index' => 14,
        'name'=>'Zapatilla deportiva logo',
        'price'=>'$2950',
        'description'=>"<br>".'Talles del 38 al 44.'."<br>".'Colores:negro, francia y rojo.'."<br>".'Marca: Puma',
        'id_category'=>3,
    ],
    15=>[
        'id_product'=> 5,
        'index' => 15,
        'name'=>'Zapatilla clasica',
        'price'=>'$1800',
        'description'=>"<br>".'Talles del 35 al 44.'."<br>".'Colores:negro y blanco.'."<br>".'Marca: Puma',
        'id_category'=>3,
    ],
    16=>[
        'id_product'=> 1,
        'index' => 16,
        'name'=>'Buzo con cierre',
        'price'=>'$1900',
        'description'=>'Talles del M al XXL.'."<br>".'Material: algodon rustico .'."<br>".'Colores:negro, melange y blanco.'."<br>".'Marca: Puma',
        'id_category'=>4,
    ],
    17=>[
        'id_product'=> 2,
        'index' => 17,
        'name'=>'Buzo clasico',
        'price'=>'$1600',
        'description'=>'Talles del M al XXL.'."<br>".'Material: algodon rustico .'."<br>".'Colores:rojo y azul.'."<br>".'Marca: Puma',
        'id_category'=>4,
    ],
    18=>[
        'id_product'=> 3,
        'index' => 18,
        'name'=>'Buzo cuello redondo',
        'price'=>'$1700',
        'description'=>'Talles del M al XXL.'."<br>".'Material: algodon rustico .'."<br>".'Colores:negro, blanco y mostaza.'."<br>".'Marca: Puma',
        'id_category'=>4,
    ],
    19=>[
        'id_product'=> 4,
        'index' => 19,
        'name'=>'Buzo tricolor estampado',
        'price'=>'$2000',
        'description'=>'Talles del S al XXL.'."<br>".'Material: algodon rustico .'."<br>".'Colores:negro y blanco.'."<br>".'Marca: Puma',
        'id_category'=>4,
    ],
    20=>[
        'id_product'=> 5,
        'index' => 20,
        'name'=>'Buzo franja',
        'price'=>'$1850',
        'description'=>'Talles del S al XXXL.'."<br>".'Material: algodon rustico .'."<br>".'Colores:negro y gris claro.'."<br>".'Marca: Puma',
        'id_category'=>4,
    ],

];
UpdateArrayFile($a_products,"json","products.json");
 ?>